### ISSUE TITLE
Error:Failed to resolve: Gitskarios.sdks:gitskarios-core:unspecified

### ISSUE THREAD

**Issue by Y-E-P** [gitskarios/GithubAndroidSdk#31]
What I can do?
```
buildscript {
    repositories {
        jcenter()
        maven {
            url  "http://dl.bintray.com/alorma/maven"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by alorma** [comment]
Hi.

In order to get Gitskarios core you should update the submodule:

```
$: git submodule update
```

**Comment by Y-E-P** [comment]
Where I must  to write this???

**Comment by alorma** [comment]
you should exexute this command n the command line, inside the root of GithubAndroidSdk

**Comment by Y-E-P** [comment]
But why I dont can use "compile" in gradle to get library???

**Comment by alorma** [comment]
because GitskariosCore is a submodule, and is not attached in the same repository.

A submodule is a astandalone repository, that is outside of GithubAndroidSDK, so you need to do `git submodule update` to get the content, before compile it from gradle

**Comment by Y-E-P** [comment]
Its not helped for me,can you write instruction step by step to integrate your SDK to my project???

**Comment by alorma** [comment]
Are you trying to use the gradle dependency? or using the code as a module of your project?

**Comment by Y-E-P** [comment]
I try to use a gradle dependency.
compile 'com.github.alorma:github-sdk:1.3.1'

**Comment by alorma** [comment]
Ok.

I will test it later, and will upload a new version of the SDK

**Comment by Y-E-P** [comment]
I hope you will fix the problem

**Comment by alorma** [comment]
Hi @Y-E-P can you check with this version:

```
compile 'com.github.alorma:github-sdk:1.5.0'
```

**Comment by Y-E-P** [comment]
If there instructions or sample code of wiki for use your library??

**Comment by alorma** [comment]
Not much.

Basic instructions can be found in the README.md

**Comment by Y-E-P** [comment]
But its incorrect. Can you rewrite it??or write there why it doesnt work

GithubReposClient client = new UserReposClient(getActivity(), username);
client.setOnResultCallback(callback);
client.execute();

**Comment by alorma** [comment]
it's basic java, not so difficult to understand why it fails
