### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by Meisolsson** [gitskarios/GithubAndroidSdk#39]
```
Error:Failed to resolve: GithubAndroidSdk:GitskariosCore:unspecified
```

Any ideas? Only happens on 2.1.0

**Comment by alorma** [comment]
Using the gradle / maven dependency?

**Comment by Meisolsson** [comment]
Gradle

**Comment by Longi94** [comment]
I'm also getting this error.

**Comment by alorma** [comment]
Hi guys.

could you try with version `2.1.1`?

**Comment by Longi94** [comment]
It issue is still present with 2.1.1 :/

My build.gradl looks like this:
[build.gradle.txt](https://github.com/gitskarios/GithubAndroidSdk/files/57058/build.gradle.txt)

**Comment by alorma** [comment]
Ok i will check later, sorry

**Comment by alorma** [comment]
Ok guys...

try with the `2.1.2`, i merged `Gitskarios-Core` into this SDK

**Comment by Longi94** [comment]
Looks like it's working. Thanks!
