### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by farbodsz** [gitskarios/GithubAndroidSdk#41]
As this project is listed on the GitHub developers page, and being the only Android SDK / API for GitHub, could you provide documentation to show how this can be used.

Ideally something similar to the example on this project's README, but showcasing all of the features and how they can be used in Android.

**Comment by alorma** [comment]
I have to add a Wiki pages for it, i will do at holidays, thanks

**Comment by farbodsz** [comment]
Thank you

**Comment by ZacSweers** [comment]
This is really necessary. The current "INIT" section of the README is not really obvious at all :/. Also, all the old 1.x authentication classes are gone, with no migration strategy.

**Comment by alorma** [comment]
I added a wiki section, check it out

**Comment by farbodsz** [comment]
Thanks.

It's a great improvement, however I was wondering whether there could be documentation on getting a list of repositories, or using other features of the SDK.

Thanks again.

**Comment by alorma** [comment]
It's in the roadmap
