### ISSUE TITLE
CommitComment gets downcast to GithubComment when parceled

### ISSUE THREAD

**Issue by ZacSweers** [gitskarios/GithubAndroidSdk#42]
Say you have a CommitComment and want to pass it as a parcel object in a bundle. When parceled, the only parceling implementation is in the parent GithubComment, which parcels its subset of the data into a GitHubComment and only passes that. Result is a crash on the other side when you try to pull out a CommitComment and only get a GitHubComment

**Comment by alorma** [comment]
oh that's not cool

i will check it as soon as i can, thanks

**Comment by alorma** [comment]
Now objects are Serialized, instead of Parcelable.

It should fix the problem.

New version: 3.0.0

**Comment by ZacSweers** [comment]
Wait what? Please don't use serializable, its implementation on Android is notoriously slow. See: http://stackoverflow.com/a/3612364/3323598

**Comment by alorma** [comment]
I know that.

But as far as it shouldn't be used as parameters (in a bundle) for a big containers (big lists etc....) it's ok.

I will think about that, but m y goal is move all SDK to pure java, so i can't use android Parcel.

If you think parcel are really needed, you can open a PR making all beans pareclable

**Comment by ZacSweers** [comment]
Why not just not serialize them at all and leave the implementation to the
user (e.g. Allow them to extend and implement parcelable or use something
like gson)? This way you're not forcing one convention over another.

**Comment by alorma** [comment]
Readded parcels.

Now ALL bens are parcelable, so no problems of casting

**Comment by alorma** [comment]
@hzsweers version 3.0.2 available please, check if the bug is fixed

**Comment by ZacSweers** [comment]
Fantastic, thanks so much!
