### ISSUE TITLE
Observables shouldn't choose subscribeOn schedulers

### ISSUE THREAD

**Issue by ZacSweers** [gitskarios/GithubAndroidSdk#44]
All the observables currently automatically choose `Schedulers.io()`. This is bad IMO, as this prevents users from using their own scheduler for these. subcribeOn will basically only work once, so it can't be overloaded.

Example:

Schedulers.io() basically spins off a new thread every time there's a new task. Not everyone wants this, and it's not uncommon to use your own bounded IO scheduler when developing in a more limited environment (aka mobile apps)

**Comment by alorma** [comment]
Uhmmm, that's ok

Could you open a PR for it? I have no much time this week.

Anyway, concat .subscribeOn(yourScheduler) should do the trick

**Comment by alorma** [comment]
Done

It will be available in the next release, today

**Comment by alorma** [comment]
Version `3.1.0` uploaded to bintray

**Comment by ZacSweers** [comment]
Great, thanks!

**Comment by alorma** [comment]
@hzsweers fixed a bug with user parcelable

**Comment by alorma** [comment]
Version 3.1.1
