### ISSUE TITLE
Payload relationship is undefined

### ISSUE THREAD

**Issue by ZacSweers** [gitskarios/GithubAndroidSdk#45]
GithubEvent objects all have a `Payload` field, but this is completely unrelated to all the *Payload beans that existed in the project before, and breaks usages where we previously casted the payload object to the appropriate type. What's their relationship, and how should these new Payload objects be used considering they don't share all the same fields as their previous Payload variants (such as `ref_type`, `target`, or `gist`).

**Comment by alorma** [comment]
I didn't changed any relations between 2.x and 3.x version

**Comment by ZacSweers** [comment]
You did from 1.x to 2.x though. Things like `IssuesPayload` are unrelated to the `payload` field in a `GitHubEvent`, and not castable. This means that information that was previously retrievable (like the fields mentioned above) now aren't accessible anywhere.

**Comment by ZacSweers** [comment]
Any word on this? I got mixed up and didn't realize gist and target were local to our project, but `ref_type` seems important and like it should be part of the `Payload`

https://github.com/gitskarios/GithubAndroidSdk/blob/develop/src/main/java/com/alorma/github/sdk/bean/dto/response/events/payload/DeleteEventPayload.java#L22

**Comment by alorma** [comment]
No, i hadn't opportunity to check it.

Please open a PR for it if it's urgent for you

**Comment by ZacSweers** [comment]
https://github.com/gitskarios/GithubAndroidSdk/pull/46

**Comment by alorma** [comment]
Uploaded `3.1.2`
