### ISSUE TITLE
How to use this sdk?

### ISSUE THREAD

**Issue by ananth10** [gitskarios/GithubAndroidSdk#48]
I need to get github user details from my android application. is it possible to get user informations, if i use this sdk? . i could not get enough information from READ ME page. could anyone  help me?

**Comment by alorma** [comment]
Hi.

Here you can find the clientes related User information.

https://github.com/gitskarios/GithubAndroidSdk/tree/develop/src/main/java/com/alorma/github/sdk/services/user

If you are looking for an authenticated user (if you have the token), you can use the 
- GetAuthUserClient.java

If you want to get anyone else information: 
- RequestUserClient.java

**Comment by ananth10** [comment]
Thanks Alorma. in my android app any user can login if they have github user name . so once user logged in means , need to get their repos list and other informations.. so how can i acheive this?

**Comment by alorma** [comment]
Repositories:
https://github.com/gitskarios/GithubAndroidSdk/tree/develop/src/main/java/com/alorma/github/sdk/services/repos

Repository information (and actions):
https://github.com/gitskarios/GithubAndroidSdk/tree/develop/src/main/java/com/alorma/github/sdk/services/repo
