### ISSUE TITLE
Need login module to get logged in user repos and their informations

### ISSUE THREAD

**Issue by ananth10** [gitskarios/GithubAndroidSdk#49]

**Comment by ghost** [comment]
What is this

**Comment by ananth10** [comment]
this sdk not have the login process. and how to get access token through git api?

**Comment by alorma** [comment]
If you download the `3.2.0` version of the sdk you have the ability to login using user and password.

Here's an example of how it works: https://github.com/gitskarios/SDK-Basic-Auth-Demo

**Comment by ananth10** [comment]
Okay. thanks alorma. let me try it.
