### ISSUE TITLE
Release and distribution

### ISSUE THREAD

**Issue by Meisolsson** [gitskarios/GithubAndroidSdk#5]
Alright now we can use the lib without compiling it locally. So do we want to use maven (jcenter) or should we implement JitPack. JitPack might be simpler for you but maven might be cleaner. It's up to you. The third option is to just release a .arr to the GitHub repo.

I know I'm a little bit stressed but I'd love to be able to use it at the GitHub app over at forkhubs :D

**Comment by alorma** [comment]
Maybe the better option is to use in jcenter.

Do you have any tutorial?

I've uploaded to mavenCentral, but never in jCenter

**Comment by Meisolsson** [comment]
I've personally never done it but it looks simple: https://bintray.com/howbintrayworks
For simpler release there's a plugin (https://github.com/novoda/bintray-release). As I said never used it so can't help you more than that.

**Comment by alorma** [comment]
Ok :)

I will try to upload a first version later today, i will tell you.

Please, if you found bugs, or have improvements, create PR to keep this SDK updated :)

**Comment by alorma** [comment]
Uhmmmm

I upload it to bintray, but when i try to compile an example, that request the BaseSDK, that is included as compile project(':sdks:BaseSdk')... weird

**Comment by Meisolsson** [comment]
Is it on jcenter?

**Comment by alorma** [comment]
I made some changes to test it, si i will not depend on BaseSDK

**Comment by Meisolsson** [comment]
So is BaseSDK gonna be removed or just for releases?

**Comment by alorma** [comment]
Read the readme, i uploaded to jCenter.

> So is BaseSDK gonna be removed or just for releases?

BaseSdk is removed, it was a try for a feature i want to implement, but not for now.

**Comment by Meisolsson** [comment]
Nice! Just FYI there is a way to have it sync directly to the main jcenter repo (Motom right in the project on bintray "Linked To")

**Comment by alorma** [comment]
> Nice! Just FYI there is a way to have it sync directly to the main jcenter repo (Motom right in the project on bintray "Linked To")

Yes, i did, but is not automatic, and we are on Saturday... you know

**Comment by hzsweers** [comment]
Thanks for all the help Bernat!
