### ISSUE TITLE
Implement Parcelable.Creator in GithubComment

### ISSUE THREAD

**Issue by aandis** [gitskarios/GithubAndroidSdk#53]
Presently, [GithubComment](https://github.com/gitskarios/GithubAndroidSdk/blob/develop/src/main/java/com/alorma/github/sdk/bean/dto/response/GithubComment.java) has a `writeToParcel()` implemented but no `Parcelable.Creator`. As a result, it ends up inheriting that from [ShaUrl](https://github.com/gitskarios/GithubAndroidSdk/blob/develop/src/main/java/com/alorma/github/sdk/bean/dto/response/ShaUrl.java). So any `GithubComment` you put in the `Parcel` gets downcasted to `ShaUrl` resulting in a crash if you attempt to get a `GithubComment` from the `Parcel`.

**Comment by alorma** [comment]
Can you please open a PR for it?

**Comment by aandis** [comment]
Just did! :)

**Comment by alorma** [comment]
Version `3.2.3` uploaded to bintray

**Comment by aandis** [comment]
:+1:
