### ISSUE TITLE
why [DEPRECATED]? any reason?

### ISSUE THREAD

**Issue by binglingziyu** [gitskarios/GithubAndroidSdk#59]

**Comment by alorma** [comment]
Hi.

Maybe a better word would be UN-MANTAINED

I started a new project, with all API, in a clean code way, retrofit2, etc...

**Comment by jeffrade** [comment]
@alorma Is the new project on github yet?

**Comment by srepollock** [comment]
Is there a new API Library for Android you're working on? Will it have API3 capabilities?

**Comment by Blaccexican** [comment]
Is this a new project?

**Comment by ketsalot1** [comment]
For the team

Keith Watson

**Comment by stuartsoft** [comment]
Seriously, what's going on here? Anyone know if there's a new Android SDK?

**Comment by letmeonplease** [comment]
No nothing
