### ISSUE TITLE
ExecuteSync still planned?

### ISSUE THREAD

**Issue by Meisolsson** [gitskarios/GithubAndroidSdk#7]
Is this something we want to implement? It looks like we would have to add two Service methods for every api call.

Nothing wrong with it just asking cause it's only returning null for the moment

**Comment by alorma** [comment]
I not need it for Gitskarios, but if you do a PR implementing it i will merge :)

Pls, one commit per service / client

**Comment by Meisolsson** [comment]
Do you want the PR based from the develop branch or master?

**Comment by alorma** [comment]
The most recent, i think it's develop branch.

Thanks

**Comment by alorma** [comment]
@Meisolsson Any news on that?

**Comment by Meisolsson** [comment]
Yeah, I'll PR tonight
On Aug 24, 2015 4:16 PM, Bernat Borrás Paronella <notifications@github.com> wrote:@Meisolsson Any news on that?
